package exercises.support;

enum Place 
{
    BETH_AND_JERRY_ROOM;
    CITADEL_OF_RICKS;
    MORTY_ROOM;
    DINING_ROOM;
    FANCY_EATS;
    HARRY_HERPSON_HIGH_SCHOOL;
    KITCHEN;
    ST_EQUIS_HOSPITAL;
    SUMMER_ROOM;
    THE_GARAGE;
    THE_LIVING_ROOM;
    YARB;
}